# Generated by Django 6.1.1 on 2026-09-12 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('asset', models.CharField(help_text='e.g. XAUUSD, EURUSD, BTCUSDT', max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('position_size', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('strategy', models.CharField(blank=True, max_length=100)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('OPEN', 'Open'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this trade belongs to. Trades are private to their owner.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['user', '-date'], name='journal_tra_user_id_4646db_idx')],
            },
        ),
    ]
